workflow:
  name: "Bluetooth Connection Workflow"
  steps:
    - name: "Connect to Bluetooth"
      action: "connect_bluetooth"
      input:
        bluetooth_device: "MySpeaker"
      output:
        connection_status: "connected"
