workflow:
  name: "Bluetooth Connection"
  steps:
    - name: "Connect to Bluetooth"
      action: "connect_bluetooth"
      input:
        bluetooth_device: "MySpeaker"
      output:
        connection_status: "connected"
    - name: "LLM Handshake"
      action: "llm_handshake"
      input:
        connection_status: "connected"
      output:
        handshake_result: "success"
