version: "3"
services:
  corebit:
    build: .
    environment:
      - PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN}
    volumes:
      - .:/app
    depends_on:
      - pulumi
  pulumi:
    image: pulumi/pulumi
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/pulumi
    entrypoint: "pulumi up"
